crva_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: CRVAUserBundle:Default:index }

crva_user_index:
    path:     /user/index
    defaults: { _controller: CRVAUserBundle:User:index }

crva_user_articles:
    path:     /user/articles/{page}
    defaults: { _controller: CRVAUserBundle:User:articles, page: 1 }
    requirements:
        page: \d+