crva_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: CRVAUserBundle:Default:index }

crva_user_index:
    path:     /user/index
    defaults: { _controller: CRVAUserBundle:User:index }

crva_user_add:
    path:     /user/add
    defaults: { _controller: CRVAUserBundle:User:add }

crva_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: CRVAUserBundle:User:edit}

crva_user_view:
    path:     /user/view/{id}
    defaults: { _controller: CRVAUserBundle:User:view}

crva_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: CRVAUserBundle:User:delete}

